const nifty50Symbols = [
  'ADANIPORTS.NS', 'APOLLOHOSP.NS', 'ASIANPAINT.NS', 'AXISBANK.NS', 'BAJAJ-AUTO.NS',
  'BAJFINANCE.NS', 'BAJAJFINSV.NS', 'BHARTIARTL.NS', 'BPCL.NS', 'BRITANNIA.NS',
  'CIPLA.NS', 'COALINDIA.NS', 'DIVISLAB.NS', 'DRREDDY.NS', 'EICHERMOT.NS',
  'GRASIM.NS', 'HCLTECH.NS', 'HDFCBANK.NS', 'HDFCLIFE.NS', 'HEROMOTOCO.NS',
  'HINDALCO.NS', 'HINDUNILVR.NS', 'ICICIBANK.NS', 'INDUSINDBK.NS', 'INFY.NS',
  'ITC.NS', 'JSWSTEEL.NS', 'KOTAKBANK.NS', 'LT.NS', 'M&M.NS',
  'MARUTI.NS', 'NESTLEIND.NS', 'NTPC.NS', 'ONGC.NS', 'PIDILITIND.NS',
  'POWERGRID.NS', 'RELIANCE.NS', 'SBILIFE.NS', 'SBIN.NS', 'SHREECEM.NS',
  'SUNPHARMA.NS', 'TATACONSUM.NS', 'TATAMOTORS.NS', 'TATASTEEL.NS', 'TECHM.NS',
  'TITAN.NS', 'UPL.NS', 'ULTRACEMCO.NS', 'WIPRO.NS', 'HDFC.NS'
];

const niftyBankSymbols = [
  'AXISBANK.NS', 'BANKBARODA.NS', 'HDFCBANK.NS', 'ICICIBANK.NS',
  'IDFCFIRSTB.NS', 'INDUSINDBK.NS', 'KOTAKBANK.NS', 'PNB.NS',
  'SBIN.NS', 'AUROPHARMA.NS', 'FEDERALBNK.NS', 'RBLBANK.NS',
  'YESBANK.NS', 'UNIONBANK.NS', 'CANBK.NS', 'BANKINDIA.NS',
  'CENTRALBK.NS', 'INDIANB.NS', 'UCOBANK.NS', 'IOB.NS',
  'MAHABANK.NS', 'DCBBANK.NS', 'SOUTHBANK.NS', 'J&KBANK.NS',
  'KARURVYSYA.NS', 'CUB.NS', 'IDBI.NS', 'REPCOHOME.NS',
  'LICHSGFIN.NS', 'MUTHOOTFIN.NS', 'BAJFINANCE.NS', 'BAJAJFINSV.NS',
  'CHOLAFIN.NS', 'HDFCLIFE.NS', 'ICICIPRULI.NS', 'SBILIFE.NS',
  'HDFC.NS', 'PFC.NS', 'RECLTD.NS', 'MANAPPURAM.NS'
];
const niftyITSymbols = [
  'TCS.NS', 'INFY.NS', 'HCLTECH.NS', 'WIPRO.NS', 'TECHM.NS',
  'LTIM.NS', 'MPHASIS.NS', 'COFORGE.NS', 'PERSISTENT.NS', 'LTI.NS',
  'BIRLASOFT.NS', 'NIITTECH.NS', 'SONATSOFTW.NS', 'MINDTREE.NS', 'ZENSARTECH.NS',
  'TATAELXSI.NS', 'CYIENT.NS', 'eCLERX.NS', 'RPSGVENT.NS', 'NEWGEN.NS',
  'SUBEX.NS', 'KELLTONTEC.NS', 'NIIITLTD.NS', 'DATAMATICS.NS', 'HAPPSTMNDS.NS',
  'XCHANGING.NS', 'INTELLECT.NS', 'TANLA.NS', 'SASKEN.NS', 'MASFIN.NS',
  'AFFLE.NS', 'KPITTECH.NS', 'FSL.NS', '3IINFOLTD.NS', 'EXPLEOSOL.NS',
  'ZENTEC.NS', 'EINFOCHIPS.NS', 'URJA.NS', 'IMPEXFERRO.NS', 'RAMCOSYS.NS'
];
const niftyMidcapSymbols = [
  'ABB.NS', 'ASHOKLEY.NS', 'BALKRISIND.NS', 'BATAINDIA.NS', 'BEL.NS',
  'CANFINHOME.NS', 'CUMMINSIND.NS', 'DIXON.NS', 'ESCORTS.NS', 'GMRINFRA.NS',
  'GODREJPROP.NS', 'GUJGASLTD.NS', 'INDIAMART.NS', 'INDIGO.NS', 'JUBLFOOD.NS',
  'KPITTECH.NS', 'LALPATHLAB.NS', 'LUXIND.NS', 'MINDTREE.NS', 'NAM-INDIA.NS',
  'NHPC.NS', 'NMDC.NS', 'OFSS.NS', 'PAGEIND.NS', 'PEL.NS',
  'PFIZER.NS', 'POLYCAB.NS', 'RAJESHEXPO.NS', 'RECLTD.NS', 'SAIL.NS',
  'SRF.NS', 'SUNTV.NS', 'SUPREMEIND.NS', 'THERMAX.NS', 'TVSMOTOR.NS',
  'UBL.NS', 'VOLTAS.NS', 'ZEEL.NS', 'ZYDUSLIFE.NS', 'IDFCFIRSTB.NS'
];
const niftySmallcapSymbols = [
  'IRB.NS', 'JINDALSAW.NS', 'TV18BRDCST.NS', 'CENTURYTEX.NS', 'RBLBANK.NS',
  'FRETAIL.NS', 'KARURVYSYA.NS', 'MAHINDCIE.NS', 'RITES.NS', 'GRAPHITE.NS',
  'SPARC.NS', 'UCOBANK.NS', 'BASF.NS', 'CENTURYPLY.NS', 'RADICO.NS',
  'JBCHEPHARM.NS', 'SEQUENT.NS', 'SFL.NS', 'IFBIND.NS', 'HFCL.NS',
  'NBCC.NS', 'MAHSCOOTER.NS', 'TANLA.NS', 'KEI.NS', 'STERTOOLS.NS',
  'ELGIEQUIP.NS', 'AMBER.NS', 'ASTERDM.NS', 'BIRLACORPN.NS', 'GMDCLTD.NS',
  'VAIBHAVGBL.NS', 'DCAL.NS', 'CREDITACC.NS', 'GSPL.NS', 'JUSTDIAL.NS',
  'ITI.NS', 'NLCINDIA.NS', 'SOLARA.NS', 'PRAJIND.NS', 'PNCINFRA.NS'
];
const niftyAutoSymbols = [
  'MARUTI.NS', 'M&M.NS', 'TATAMOTORS.NS', 'BAJAJ-AUTO.NS', 'EICHERMOT.NS',
  'TVSMOTOR.NS', 'MOTHERSON.NS', 'BOSCHLTD.NS', 'HEROMOTOCO.NS', 'ASHOKLEY.NS',
  'MRF.NS', 'BHARATFORG.NS', 'TIINDIA.NS', 'BALKRISIND.NS', 'EXIDEIND.NS',
  'APOLLOTYRE.NS', 'CEATLTD.NS', 'JKTYRE.NS', 'AMARAJABAT.NS', 'SONACOMS.NS',
  'ENDURANCE.NS', 'VARROC.NS', 'MINDAIND.NS', 'SUNCLAYLTD.NS', 'WABCOINDIA.NS',
  'RANEHOLDIN.NS', 'SUPRAJIT.NS', 'JBMA.NS', 'LUMAXIND.NS', 'SANDHAR.NS',
  'GABRIEL.NS', 'SETCO.NS', 'PRICOLLTD.NS', 'SUBROS.NS', 'JAMNAAUTO.NS',
  'MAHINDCIE.NS', 'SMLISUZU.NS', 'HINDCOMPOS.NS', 'TALBROAUTO.NS', 'ZFCVINDIA.NS'
];
module.exports = {
  nifty50Symbols,
    niftyBankSymbols,
  niftyITSymbols,
  niftyMidcapSymbols,
  niftySmallcapSymbols,
  niftyAutoSymbols
};